const dotenv = require("dotenv");
const path = require("path");

dotenv.config({
  path: path.resolve(__dirname, `${process.env.NODE_ENV}.env`),
});


module.exports = {
  NODE_ENV: process.env.NODE_ENV,
  PORT: process.env.PORT,
  BASE_URL: process.env.BASE_URL,
  LAUNCHING_MAIL:process.env.LAUNCHING_MAIL,
  VERIFY_EMAIL:process.env.VERIFY_EMAIL,
  apiKey: process.env.apiKey,
  authDomain: process.env.authDomain,
  databaseURL: process.env.databaseURL,
  projectId: process.env.projectId,
  storageBucket: process.env.storageBucket,
  messagingSenderId: process.env.messagingSenderId,
  appId: process.env.appId,
  FIRESTORE_URL: process.env.FIRESTORE_URL,
  RAPID_USERINFO_URL: process.env.RAPID_USERINFO_URL,
  RAPID_USERINFO_URL_V2: process.env.RAPID_USERINFO_URL_V2,
  RapidAPIKey_V2: process.env.RapidAPIKey_V2,
  RapidAPIHost_V2: process.env.RapidAPIHost_V2,
  RapidAPIKey: process.env.RapidAPIKey,
  RapidAPIHost: process.env.RapidAPIHost,
  SPREADSHEET: process.env.SPREADSHEET,
  SPREADSHEET_URL: process.env.SPREADSHEET_URL,
  KEY_ID: process.env.KEY_ID,
  KEY_SECRET: process.env.KEY_SECRET,
  WEBHOOK_SECRET: process.env.WEBHOOK_SECRET,
  PLNIMPCAFE6:process.env.PLNIMPCAFE6,
  PLNCMPCAFE6:process.env.PLNCMPCAFE6,
  PLNIMPCLUB6:process.env.PLNIMPCLUB6,
  PLNCMPCLUB6:process.env.PLNCMPCLUB6,
  PLNIMPBOOTH6:process.env.PLNIMPBOOTH6,
  PLNCMPBOOTH6:process.env.PLNCMPBOOTH6,
  PLNIMPSALON6:process.env.PLNIMPSALON6,
  PLNCMPSALON6:process.env.PLNCMPSALON6,
  PLNIMPGYM6:process.env.PLNIMPGYM6,
  PLNCMPGYM6:process.env.PLNCMPGYM6,
  PLNIMPPROFESSIONAL6:process.env.PLNIMPPROFESSIONAL6,
  PLNCMPPROFESSIONAL6:process.env.PLNCMPPROFESSIONAL6,
  PLNIMPCAFE12:process.env.PLNIMPCAFE12,
  PLNCMPCAFE12:process.env.PLNCMPCAFE12,
  PLNIMPCLUB12:process.env.PLNIMPCLUB12,
  PLNCMPCLUB12:process.env.PLNCMPCLUB12,
  PLNIMPBOOTH12:process.env.PLNIMPBOOTH12,
  PLNCMPBOOTH12:process.env.PLNCMPBOOTH12,
  PLNIMPSALON12:process.env.PLNIMPSALON12,
  PLNCMPSALON12:process.env.PLNCMPSALON12,
  PLNIMPGYM12:process.env.PLNIMPGYM12,
  PLNCMPGYM12:process.env.PLNCMPGYM12,
  PLNIMPPROFESSIONAL12:process.env.PLNIMPPROFESSIONAL12,
  PLNCMPPROFESSIONAL12:process.env.PLNCMPPROFESSIONAL12,
  MEM_AMOUNT: process.env.MEM_AMOUNT,
  FRNT_SUBSCRIPTION_HEADING: process.env.FRNT_SUBSCRIPTION_HEADING,
  FRNT_MEMBERSHIP_HEADING: process.env.FRNT_MEMBERSHIP_HEADING,
  ADMIN_BRAND_FILTER_TEXT: process.env.ADMIN_BRAND_FILTER_TEXT,
  ADMIN_EVENT_FILTER_TEXT: process.env.ADMIN_EVENT_FILTER_TEXT,
  ADMIN_COUPON_FILTER_TEXT: process.env.ADMIN_COUPON_FILTER_TEXT,
  ADMIN_INFLUENCER_FILTER_TEXT: process.env.ADMIN_INFLUENCER_FILTER_TEXT,
  WAPP_SENDMESSTEXT_UATURL_PRMNTOKN:
    process.env.WAPP_SENDMESSTEXT_UATURL_PRMNTOKN,
  WAPP_AUTH_PRMNTOKN: process.env.WAPP_AUTH_PRMNTOKN,
  EML_USER: process.env.EML_USER,
  EML_PASS: process.env.EML_PASS,
  EML_PROVIDER: process.env.EML_PROVIDER,
  EML_HREF_WEBSITE:process.env.EML_HREF_WEBSITE
};
